version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - comaiz-admin
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email your-email@domain.com --agree-tos --no-eff-email -d your-domain.com -d www.your-domain.com

  comaiz-admin:
    image: ghcr.io/danbowker/comaiz-admin/comaiz-admin:latest
    container_name: comaiz-admin
    ports:
      - "8080:8080"
    environment:
      - Jwt__Authority=${JWT_AUTHORITY}
      - Jwt__Audience=${JWT_AUDIENCE}
      - ConnectionStrings__PostgresSQL=${CONNECTION_STRING}
    restart: unless-stopped