services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    network_mode: service:db
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=7057
      - ConnectionStrings__PostgresSQL=Host=localhost;Port=5432;Username=postgres;Password=devpassword;Database=comaiz

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: comaiz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: